# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto_pb2 as proto__pb2


class ClocksServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestTimeDiff = channel.unary_unary(
                '/clocks.ClocksServer/RequestTimeDiff',
                request_serializer=proto__pb2.TimeDiffRequest.SerializeToString,
                response_deserializer=proto__pb2.TimeDiffResponse.FromString,
                )
        self.RequestTimeAjust = channel.unary_unary(
                '/clocks.ClocksServer/RequestTimeAjust',
                request_serializer=proto__pb2.TimeAjustRequest.SerializeToString,
                response_deserializer=proto__pb2.TimeAjustResponse.FromString,
                )


class ClocksServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestTimeDiff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestTimeAjust(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClocksServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestTimeDiff': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTimeDiff,
                    request_deserializer=proto__pb2.TimeDiffRequest.FromString,
                    response_serializer=proto__pb2.TimeDiffResponse.SerializeToString,
            ),
            'RequestTimeAjust': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTimeAjust,
                    request_deserializer=proto__pb2.TimeAjustRequest.FromString,
                    response_serializer=proto__pb2.TimeAjustResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clocks.ClocksServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClocksServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestTimeDiff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clocks.ClocksServer/RequestTimeDiff',
            proto__pb2.TimeDiffRequest.SerializeToString,
            proto__pb2.TimeDiffResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestTimeAjust(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clocks.ClocksServer/RequestTimeAjust',
            proto__pb2.TimeAjustRequest.SerializeToString,
            proto__pb2.TimeAjustResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
